apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-87dq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-87dq@sha256:86415a9d2748847945852b5aa8035ad626bb407c4cbf8c427c903277420cdbd0
        name: my-nodejs
        resources: {}
status: {}
